version: "3.4"
services:
  app:
    build: .
    image: patnaikshekhar/b2cexample
    ports:
    - 8000:8000
    environment:
      MONGO_URL: mongodb://mongo:mongo@db/employees
    links:
    - db
  db:
    image: mongo
    volumes:
    - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

