apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2bdemo
  namespace: identity-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b2bdemo
  template:
    metadata:
      name: b2bdemo
      labels:
        app: b2bdemo
    spec:
      containers:
      - image: patnaikshekhar/b2binvitationdemo:1.10
        name: main-app
        envFrom:
        - secretRef:
            name: b2b-demo-secrets
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: b2b-demo-secrets
